// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MindAttic.Ideas.Core.Data;

#nullable disable

namespace MindAttic.Ideas.Core.Migrations
{
    [DbContext(typeof(CmsDbContext))]
    [Migration("20260616000000_AddPluginComponentKindSplit")]
    partial class AddPluginComponentKindSplit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot intentionally minimal — this migration was authored without a snapshot file.
            // EF only needs the [Migration] attribute to order and apply this migration; the full
            // snapshot is carried by the next auto-generated migration's Designer file.
        }
    }
}
