// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MindAttic.Ideas.Core.Data;

#nullable disable

namespace MindAttic.Ideas.Core.Migrations
{
    [DbContext(typeof(CmsDbContext))]
    [Migration("20260629200000_AddPageOpenInNewWindow")]
    partial class AddPageOpenInNewWindow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
